Scalars, Vectors, 1-D, 2-D, 3-D tensors

Constants and Variables

Creating random tensors


In [ ]:
### To concatenate two or more values, use commas(,) instead of the plus sign (+).

### Add " .numpy. " to shorten the output for certain commands such as "tens1.size.numpy"

In [ ]:
import numpy as np

tens1 = tf.constant([[1,2,3],[4,5,6]])
tf.size(tens1), "with .numpy() ", tf.size(tens1).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=6>, 'with .numpy() ', 6)

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
tensor1 = tf.constant([1])
tensor2 = tf.constant([1,2])
tensor3 = tf.constant([[1,2],[3,4]])
# tensor1.ndim
# tensor2.ndim
tensor3.ndim

2

In [ ]:
#specifying datatype
myMatrix = tf.constant([[1,2,3.7],[4.5,5.4,6.3]], dtype = tf.float32)
myMatrix.ndim

2

In [ ]:
#datatype automatically changes according to allocation
matrix2 = tf.constant([[1,2,3.4],[4.3,5.4,6.3]])
matrix2.dtype

tf.float32

In [ ]:
#creating a degree 3 tensor
d3tensor = tf.constant([[[1,23,4],
                        [4,5,6],
                       [7,8,9]]
                        ,[[9,10,11],
                        [12,13,14],
                        [13,14,15]]])
# d3tensor
d3tensor.ndim

3

In [ ]:
a = tf.Variable([10,7])
a.assign([2,9])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 9], dtype=int32)>

In [ ]:
#creating a random tensor

random1 = tf.random.Generator.from_seed(seed=32)
random1 = random1.normal(shape = (2,3))


random2 = tf.random.Generator.from_seed(seed=42)
random2 = random2.normal (shape = (2,3))

random1, random2, random1 == random2

##IMPORTANT

# If you create two randoms tensors with the same seed value,
# and the same shape, they will have the same elements.

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.7901182,  1.585549 ,  0.4356279],
        [ 0.2364518, -0.1589871,  1.302304 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False, False],
        [False, False, False]])>)

In [ ]:
#Shuffling a tensor

mytensor = tf.constant([[10,3],[5,2],[7,1]])


##Setting a random seed value
tf.random.set_seed(seed = 42)
tf.random.shuffle(mytensor, seed = 42)

##If both the global (Line 2) and the operation level seed
##values are the same, then we end up with the same tensor

# To shuffle, the sequence of elements try using diff values
# for global seed and the operational level seed.

#OR, use no seed at all. That way, tensorflow will automatically
#pick some random seed and shuffle your tensor elements based on
#that distribution.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  2],
       [ 7,  1],
       [10,  3]], dtype=int32)>

In [ ]:
 #Creating a tensor filled with Ones

 myOnes = tf.ones(shape=(2,3))
 myOnes

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#Converting numpy arrays into tensors

## Difference between a numpy array and a tensor
## is that a tensor can run on a GPU, which is
## computationally faster

## AND tensorflow uses computation graph, hence
## resulting in faster computations

## Tensorflow also comes with the ability to
## compute backward prop and gradients too,
## just by observing the flow of data during
## forward prop in the algorithm

import numpy as np

A = np.arange(1,25);

A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
tensA = tf.constant(A, shape = (1,3,8))
tensA.numpy(), tensA.ndim

(array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16],
         [17, 18, 19, 20, 21, 22, 23, 24]]]),
 3)

In [ ]:
tensA.shape

TensorShape([1, 3, 8])

In [ ]:
tf.shape(tensA)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 8], dtype=int32)>

In [ ]:
tf.size(tensA)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
# Trying to find the first two elements of every dimension of a tensor with dimensions (2,3,4,5)

A = np.arange(1,121)

myT = tf.constant(A)
myTnew = tf.reshape(A,(2,3,4,5))
print(myTnew[:2,:2,:2,:2])


#Trying to print the first elements from all dimensions except the final one

print(myTnew[:1,:1,:1,:])

tf.Tensor([[[[1 2 3 4 5]]]], shape=(1, 1, 1, 5), dtype=int64)


In [ ]:
# Creating a Rank 3 tensor out of a Rank-2 tensor

rank2 = tf.constant([[2,3],[4,5],[6,7]])
rank2

rank3 = tf.reshape(rank2, (1,1,6))
rank3

<tf.Tensor: shape=(1, 1, 6), dtype=int32, numpy=array([[[2, 3, 4, 5, 6, 7]]], dtype=int32)>