In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Matrix Mutltiplication

A = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
B = tf.constant([[7],
                 [8],
                 [9]])

A_transpose = tf.transpose(A)
# A_transpose

product = tf.matmul(A_transpose, B)
product

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 76],
       [100]], dtype=int32)>

In [ ]:
#Finding sum, max, min, var, stdv

E = tf.random.Generator.from_seed(seed = 42)
E = tf.constant(np.random.randint(0,12, size = 6))


max = tf.reduce_max(E).numpy()
min = tf.reduce_min(E).numpy()
sum = tf.reduce_sum(E).numpy()

E, max, min, sum

(<tf.Tensor: shape=(6,), dtype=int64, numpy=array([ 7,  9, 11,  6,  6,  1])>,
 11,
 1,
 40)

In [ ]:
#Finding variance and standard deviation

import tensorflow_probability as tfp

var = tfp.stats.variance(E)
var2 = tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

std = tf.math.reduce_std(tf.cast(E, dtype = tf.float32))


var.numpy(), var2.numpy(), std.numpy()



(10, 9.555556, 3.0912063)

In [ ]:
#Finding positional max and min

F = tf.random.Generator.from_seed(seed = 42)
F = F.uniform(shape = (5,4))

F

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817],
       [0.1889317 , 0.52027524, 0.8736881 , 0.46921718],
       [0.63932586, 0.6467117 , 0.96246755, 0.41009164],
       [0.86540747, 0.8862978 , 0.27795732, 0.8857763 ],
       [0.2179842 , 0.29115117, 0.03953862, 0.8136791 ]], dtype=float32)>

In [ ]:
tf.argmax(F)  #prints the index of the maximum value in F


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([3, 3, 2, 3])>

In [ ]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
#Squeezing a tensor

G = tf.random.Generator.from_seed(seed = 42)
G = G.uniform(shape = ([1,1,1,50]))

G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
          0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
          0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
          0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
          0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
          0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
          0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
          0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
          0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
          0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 50])

In [ ]:
G_sqzd = tf.squeeze(G)
G_sqzd, G_sqzd.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
        0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ,
        0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732,
        0.8857763 , 0.2179842 , 0.29115117, 0.03953862, 0.8136791 ,
        0.8139852 , 0.52180684, 0.12496924, 0.5488483 , 0.7755773 ,
        0.6184403 , 0.24936223, 0.89341843, 0.28422844, 0.70332646,
        0.2622137 , 0.4432162 , 0.466465  , 0.05981874, 0.40098202,
        0.69292355, 0.1284684 , 0.22770369, 0.33691216, 0.5329138 ,
        0.5914326 , 0.21738243, 0.5322075 , 0.05148339, 0.03951418,
        0.41866875, 0.78939915, 0.04384279, 0.96955836, 0.49116182],
       dtype=float32)>,
 TensorShape([50]))

In [ ]:
#One-hot encoding

my_list = [0,1,2,3]

encoded = tf.one_hot(my_list, depth = 4)
encoded

encoded2 = tf.one_hot(my_list, depth = 4, on_value = "true", off_value = "false")
encoded2

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'true', b'false', b'false', b'false'],
       [b'false', b'true', b'false', b'false'],
       [b'false', b'false', b'true', b'false'],
       [b'false', b'false', b'false', b'true']], dtype=object)>

In [ ]:
#Square, log, sqrt

#Creating a new tensor

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
sqd = tf.square(H)
sqd

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
sqrt = tf.sqrt(tf.cast(H, dtype = tf.float32))
sqrt = tf.reshape(sqrt, shape = (3,3))
sqrt

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898],
       [2.6457512, 2.828427 , 3.       ]], dtype=float32)>